# Generated by Django 5.0.6 on 2024-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsview_news_news_likes_news_views_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
